{
  "resourceType": "Condition",
  "id": "covid-19-cdcc",
  "meta": {
    "profile": [ "http://hl7.org/fhir/us/qicore/StructureDefinition/qicore-condition" ]
  },
  "category": [ {
    "coding": [ {
      "system": "http://terminology.hl7.org/CodeSystem/condition-category",
      "code": "encounter-diagnosis",
      "display": "Encounter Diagnosis"
    } ]
  } ],
  "code": {
    "coding": [ {
      "system": "http://snomed.info/sct",
      "version": "2022-09",
      "code": "1017214008",
      "display": "Viremia caused by severe acute respiratory syndrome coronavirus 2 (disorder)",
      "userSelected": true
    } ]
  },
  "subject": {
    "reference": "Patient/827b2df0-8ceb-4e95-8f5d-ebc96919d107"
  },
  "recordedDate": "2025-03-15T08:00:00.000+00:00"
}